// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your API Goes Here',
    appId: '1:361874230333:web:71d2d2d1f67449b96fee54',
    messagingSenderId: '361874230333',
    projectId: 'tiku-winner-gaming',
    authDomain: 'tiku-winner-gaming.firebaseapp.com',
    storageBucket: 'tiku-winner-gaming.firebasestorage.app',
    measurementId: 'G-ZZDT5BVMRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your API Goes Here',
    appId: '1:361874230333:android:3a1d722747084a216fee54',
    messagingSenderId: '361874230333',
    projectId: 'tiku-winner-gaming',
    storageBucket: 'tiku-winner-gaming.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your API Goes Here',
    appId: '1:361874230333:ios:a46abfd9fdcff0076fee54',
    messagingSenderId: '361874230333',
    projectId: 'tiku-winner-gaming',
    storageBucket: 'tiku-winner-gaming.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagement',
  );

}